### PR TITLE
Updated with lower case letters

### PR DESCRIPTION
**Pull request by spu7nik**
Did some lower case letters. They are not perfect but it's something

### CODE REVIEW

**Comment by spu7nik** [comment]
[xkcd_font.pdf](https://github.com/ipython/xkcd-font/files/794531/xkcd_font.pdf)
PDF with preview

**Comment by rgbkrk** [comment]
Nice! They could probably be a bit thicker, I think this works alright though. Did you work from the glyphs that @randallmunroe sent?

**Comment by spu7nik** [comment]
Yes, the original ones (not edited) from this repository. Do they have to be slightly thicker, or the capital ones smaller? Maybe we ask Randall...

**Comment by rgbkrk** [comment]
If they're straight from the samples provided, let's go with them. I mostly remarked from a brief glance. Thank you @spu7nik.

**Pull request merged**
